---
image: Visual Studio 2017
build: false
version: '{build}'

platform:
  - x64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
  matrix:
    - cpu: x86_64
      toolchain: gnu
      channel: nightly
    - cpu: i686
      toolchain: gnu
      channel: nightly
    - cpu: x86_64
      toolchain: msvc
      channel: nightly
    - cpu: i686
      toolchain: msvc
      channel: nightly
    - cpu: x86_64
      toolchain: gnu
      channel: stable
    - cpu: i686
      toolchain: gnu
      channel: stable
    - cpu: x86_64
      toolchain: msvc
      channel: stable
    - cpu: i686
      toolchain: msvc
      channel: stable
    - cpu: x86_64
      toolchain: gnu
      channel: beta
    - cpu: i686
      toolchain: gnu
      channel: beta
    - cpu: x86_64
      toolchain: msvc
      channel: beta
    - cpu: i686
      toolchain: msvc
      channel: beta
    - cpu: x86_64
      toolchain: gnu
      channel: 1.30.0
    - cpu: i686
      toolchain: gnu
      channel: 1.30.0
    - cpu: x86_64
      toolchain: msvc
      channel: 1.30.0
    - cpu: i686
      toolchain: msvc
      channel: 1.30.0

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - set target=%cpu%-pc-windows-%toolchain%
  - rustup-init.exe --default-host %target% --default-toolchain %channel% -y
  - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - pacman --noconfirm -S automake autoconf texinfo mingw-w64-%cpu%-clang libtool
  - rustc -Vv
  - cargo -V
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

cache:
  - C:\Users\appveyor\.cargo
  - compiler\vendor

test_script:
  - cargo build --verbose
  - cargo test
